# Generated by Django 5.0.7 on 2025-10-04 15:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("modules", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MenuItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "eid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Identifiant unique pour les intégrations externes",
                        unique=True,
                        verbose_name="External ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Créé le"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="Modifié le"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Marqué comme supprimé (soft delete)",
                        verbose_name="Supprimé",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Supprimé le"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Données additionnelles au format JSON",
                        verbose_name="Métadonnées",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True, max_length=50, unique=True, verbose_name="Code"
                    ),
                ),
                ("label", models.CharField(max_length=100, verbose_name="Libellé")),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Nom de l'icône UI5",
                        max_length=50,
                        verbose_name="Icône",
                    ),
                ),
                (
                    "path",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="URL ou route",
                        max_length=200,
                        verbose_name="Chemin",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Ordre")),
                (
                    "design",
                    models.CharField(
                        choices=[("Default", "Par défaut"), ("Action", "Action")],
                        default="Default",
                        max_length=20,
                        verbose_name="Design",
                    ),
                ),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("item", "Élément normal"),
                            ("fixed", "Élément fixe"),
                            ("separator", "Séparateur"),
                        ],
                        default="item",
                        max_length=20,
                        verbose_name="Type",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "is_system",
                    models.BooleanField(
                        default=False,
                        help_text="Élément système non modifiable",
                        verbose_name="Élément système",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Supprimé par",
                    ),
                ),
                (
                    "module",
                    models.ForeignKey(
                        blank=True,
                        help_text="Module qui fournit cet élément",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="menu_items",
                        to="modules.module",
                        verbose_name="Module",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="users.menuitem",
                        verbose_name="Parent",
                    ),
                ),
                (
                    "required_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Permissions nécessaires pour voir cet élément",
                        related_name="menu_items",
                        to="users.permission",
                        verbose_name="Permissions requises",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifié par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Élément de menu",
                "verbose_name_plural": "Éléments de menu",
                "ordering": ["order", "label"],
            },
        ),
        migrations.CreateModel(
            name="UIPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "eid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Identifiant unique pour les intégrations externes",
                        unique=True,
                        verbose_name="External ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Créé le"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="Modifié le"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Marqué comme supprimé (soft delete)",
                        verbose_name="Supprimé",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Supprimé le"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Données additionnelles au format JSON",
                        verbose_name="Métadonnées",
                    ),
                ),
                (
                    "compact_mode",
                    models.BooleanField(
                        default=False,
                        help_text="Affichage compact de l'interface",
                        verbose_name="Mode compact",
                    ),
                ),
                (
                    "sidebar_collapsed",
                    models.BooleanField(
                        default=False, verbose_name="Barre latérale réduite"
                    ),
                ),
                (
                    "show_tooltips",
                    models.BooleanField(
                        default=True, verbose_name="Afficher les infobulles"
                    ),
                ),
                (
                    "show_search",
                    models.BooleanField(
                        default=True, verbose_name="Afficher la recherche"
                    ),
                ),
                (
                    "show_notifications",
                    models.BooleanField(
                        default=True, verbose_name="Afficher les notifications"
                    ),
                ),
                (
                    "show_help",
                    models.BooleanField(default=True, verbose_name="Afficher l'aide"),
                ),
                (
                    "visible_menu_items",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Liste des codes d'éléments de menu à afficher",
                        verbose_name="Éléments de menu visibles",
                    ),
                ),
                (
                    "dashboard_layout",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Configuration des widgets et leur position",
                        verbose_name="Disposition du tableau de bord",
                    ),
                ),
                (
                    "default_page_size",
                    models.PositiveIntegerField(
                        default=20,
                        help_text="Nombre d'éléments par page dans les tableaux",
                        verbose_name="Taille de page par défaut",
                    ),
                ),
                (
                    "custom_shortcuts",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Raccourcis clavier personnalisés",
                        verbose_name="Raccourcis personnalisés",
                    ),
                ),
                (
                    "favorite_widgets",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Liste des widgets à afficher en priorité",
                        verbose_name="Widgets favoris",
                    ),
                ),
                (
                    "home_page",
                    models.CharField(
                        default="/dashboard",
                        help_text="URL de la page d'accueil par défaut",
                        max_length=100,
                        verbose_name="Page d'accueil",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Supprimé par",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifié par",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ui_preferences",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Préférence d'interface",
                "verbose_name_plural": "Préférences d'interface",
            },
        ),
    ]
