"""Asset Registry — full hierarchical model with PostGIS.

Creates 30+ tables for the O&G asset registry:
Field → Site → Installation → Equipment → Specialized specs.
Pipelines, waypoints, connections, crane load charts, separator nozzles, etc.

Revision ID: 066
Revises: 065
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = "066"
down_revision = "065"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Ensure PostGIS is available
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")

    # ── HIERARCHY ──────────────────────────────────────────────

    op.create_table(
        "ar_fields",
        sa.Column("id", postgresql.UUID(as_uuid=True), server_default=sa.text("gen_random_uuid()"), primary_key=True),
        sa.Column("entity_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("entities.id"), nullable=False),
        sa.Column("code", sa.String(30), nullable=False),
        sa.Column("name", sa.String(200), nullable=False),
        sa.Column("country", sa.String(3), nullable=False),
        sa.Column("basin", sa.String(100)),
        sa.Column("block_name", sa.String(100)),
        sa.Column("license_number", sa.String(100)),
        sa.Column("license_type", sa.String(30)),
        sa.Column("license_expiry_date", sa.Date),
        sa.Column("operator", sa.String(100), server_default="Perenco"),
        sa.Column("working_interest_pct", sa.Numeric(5, 2)),
        sa.Column("regulator", sa.String(100)),
        sa.Column("environment", sa.String(30)),
        sa.Column("centroid_latitude", sa.Numeric(12, 8)),
        sa.Column("centroid_longitude", sa.Numeric(12, 8)),
        sa.Column("area_km2", sa.Numeric(10, 4)),
        sa.Column("discovery_year", sa.Integer),
        sa.Column("first_production_year", sa.Integer),
        sa.Column("reservoir_formation", sa.String(100)),
        sa.Column("original_oil_in_place_mmbo", sa.Numeric(12, 3)),
        sa.Column("recoverable_reserves_mmbo", sa.Numeric(12, 3)),
        sa.Column("status", sa.String(30), server_default="OPERATIONAL", nullable=False),
        sa.Column("notes", sa.Text),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column("deleted_at", sa.DateTime(timezone=True)),
        sa.UniqueConstraint("entity_id", "code", name="uq_ar_fields_entity_code"),
    )
    op.create_index("idx_ar_fields_entity", "ar_fields", ["entity_id"])
    # PostGIS columns
    op.execute("ALTER TABLE ar_fields ADD COLUMN geom_centroid geography(POINT, 4326)")
    op.execute("ALTER TABLE ar_fields ADD COLUMN geom_boundary geography(POLYGON, 4326)")
    op.execute("CREATE INDEX idx_ar_fields_geom ON ar_fields USING GIST(geom_boundary)")

    op.create_table(
        "ar_sites",
        sa.Column("id", postgresql.UUID(as_uuid=True), server_default=sa.text("gen_random_uuid()"), primary_key=True),
        sa.Column("entity_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("entities.id"), nullable=False),
        sa.Column("field_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("ar_fields.id"), nullable=False),
        sa.Column("code", sa.String(30), nullable=False),
        sa.Column("name", sa.String(200), nullable=False),
        sa.Column("site_type", sa.String(50), nullable=False),
        sa.Column("environment", sa.String(30), nullable=False),
        sa.Column("latitude", sa.Numeric(12, 8)),
        sa.Column("longitude", sa.Numeric(12, 8)),
        sa.Column("country", sa.String(3), nullable=False),
        sa.Column("region", sa.String(100)),
        sa.Column("water_depth_m", sa.Numeric(8, 2)),
        sa.Column("access_road", sa.Boolean, server_default="false", nullable=False),
        sa.Column("access_helicopter", sa.Boolean, server_default="false", nullable=False),
        sa.Column("access_vessel", sa.Boolean, server_default="false", nullable=False),
        sa.Column("helideck_available", sa.Boolean, server_default="false", nullable=False),
        sa.Column("nearest_airport", sa.String(100)),
        sa.Column("nearest_port", sa.String(100)),
        sa.Column("manned", sa.Boolean, server_default="true", nullable=False),
        sa.Column("pob_capacity", sa.Integer),
        sa.Column("power_source", sa.String(100)),
        sa.Column("comms_system", sa.String(200)),
        sa.Column("max_wind_speed_ms", sa.Numeric(5, 2)),
        sa.Column("design_wave_height_m", sa.Numeric(5, 2)),
        sa.Column("design_temp_max_c", sa.Numeric(5, 2)),
        sa.Column("design_temp_min_c", sa.Numeric(5, 2)),
        sa.Column("seismic_zone", sa.String(20)),
        sa.Column("status", sa.String(30), server_default="OPERATIONAL", nullable=False),
        sa.Column("commissioning_date", sa.Date),
        sa.Column("first_oil_date", sa.Date),
        sa.Column("notes", sa.Text),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column("deleted_at", sa.DateTime(timezone=True)),
        sa.UniqueConstraint("entity_id", "code", name="uq_ar_sites_entity_code"),
    )
    op.create_index("idx_ar_sites_entity", "ar_sites", ["entity_id"])
    op.create_index("idx_ar_sites_field", "ar_sites", ["field_id"])
    op.execute("ALTER TABLE ar_sites ADD COLUMN geom_point geography(POINT, 4326)")
    op.execute("ALTER TABLE ar_sites ADD COLUMN geom_boundary geography(POLYGON, 4326)")
    op.execute("CREATE INDEX idx_ar_sites_geom ON ar_sites USING GIST(geom_boundary)")

    op.create_table(
        "ar_installations",
        sa.Column("id", postgresql.UUID(as_uuid=True), server_default=sa.text("gen_random_uuid()"), primary_key=True),
        sa.Column("entity_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("entities.id"), nullable=False),
        sa.Column("site_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("ar_sites.id"), nullable=False),
        sa.Column("code", sa.String(30), nullable=False),
        sa.Column("name", sa.String(200), nullable=False),
        sa.Column("installation_type", sa.String(60), nullable=False),
        sa.Column("environment", sa.String(30), nullable=False),
        sa.Column("latitude", sa.Numeric(12, 8)),
        sa.Column("longitude", sa.Numeric(12, 8)),
        sa.Column("elevation_masl", sa.Numeric(8, 2)),
        sa.Column("water_depth_m", sa.Numeric(8, 2)),
        sa.Column("air_gap_m", sa.Numeric(6, 2)),
        sa.Column("orientation_deg", sa.Numeric(6, 2)),
        sa.Column("local_origin_lat", sa.Numeric(12, 8)),
        sa.Column("local_origin_lon", sa.Numeric(12, 8)),
        sa.Column("local_origin_elev_m", sa.Numeric(8, 2)),
        sa.Column("status", sa.String(30), server_default="OPERATIONAL", nullable=False),
        sa.Column("installation_date", sa.Date),
        sa.Column("commissioning_date", sa.Date),
        sa.Column("first_oil_date", sa.Date),
        sa.Column("design_life_years", sa.Integer),
        sa.Column("is_manned", sa.Boolean, server_default="true", nullable=False),
        sa.Column("is_normally_unmanned", sa.Boolean, server_default="false", nullable=False),
        sa.Column("pob_max", sa.Integer),
        sa.Column("helideck_available", sa.Boolean, server_default="false", nullable=False),
        sa.Column("lifeboat_capacity", sa.Integer),
        sa.Column("total_area_m2", sa.Numeric(10, 2)),
        sa.Column("footprint_length_m", sa.Numeric(8, 2)),
        sa.Column("footprint_width_m", sa.Numeric(8, 2)),
        sa.Column("design_code", sa.String(100)),
        sa.Column("classification_society", sa.String(30)),
        sa.Column("class_notation", sa.String(100)),
        sa.Column("installation_manager", postgresql.UUID(as_uuid=True)),
        sa.Column("notes", sa.Text),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column("deleted_at", sa.DateTime(timezone=True)),
        sa.UniqueConstraint("entity_id", "code", name="uq_ar_installations_entity_code"),
    )
    op.create_index("idx_ar_installations_entity", "ar_installations", ["entity_id"])
    op.create_index("idx_ar_installations_site", "ar_installations", ["site_id"])
    op.execute("ALTER TABLE ar_installations ADD COLUMN geom_point geography(POINT, 4326)")
    op.execute("ALTER TABLE ar_installations ADD COLUMN geom_footprint geography(POLYGON, 4326)")
    op.execute("CREATE INDEX idx_ar_installations_geom ON ar_installations USING GIST(geom_footprint)")

    # ── INSTALLATION DETAILS (1:1) ─────────────────────────────

    op.create_table(
        "ar_installation_offshore_details",
        sa.Column("id", postgresql.UUID(as_uuid=True), sa.ForeignKey("ar_installations.id", ondelete="CASCADE"), primary_key=True),
        sa.Column("structure_type", sa.String(30)),
        sa.Column("jacket_leg_count", sa.Integer),
        sa.Column("topsides_weight_tonnes", sa.Numeric(10, 2)),
        sa.Column("total_weight_tonnes", sa.Numeric(10, 2)),
        sa.Column("number_of_decks", sa.Integer),
        sa.Column("main_deck_elevation_m", sa.Numeric(7, 2)),
        sa.Column("cellar_deck_elevation_m", sa.Numeric(7, 2)),
        sa.Column("top_deck_elevation_m", sa.Numeric(7, 2)),
        sa.Column("max_deck_load_tm2", sa.Numeric(6, 2)),
        sa.Column("mooring_type", sa.String(30)),
        sa.Column("number_of_mooring_lines", sa.Integer),
        sa.Column("pile_count", sa.Integer),
        sa.Column("pile_diameter_mm", sa.Numeric(7, 2)),
        sa.Column("pile_penetration_m", sa.Numeric(8, 2)),
        sa.Column("conductor_slots_total", sa.Integer),
        sa.Column("conductor_slots_used", sa.Integer),
        sa.Column("vessel_length_m", sa.Numeric(8, 2)),
        sa.Column("vessel_beam_m", sa.Numeric(7, 2)),
        sa.Column("storage_capacity_bbl", sa.Numeric(12, 2)),
        sa.Column("cp_type", sa.String(30)),
        sa.Column("cp_design_life_years", sa.Integer),
    )

    op.create_table(
        "ar_installation_onshore_details",
        sa.Column("id", postgresql.UUID(as_uuid=True), sa.ForeignKey("ar_installations.id", ondelete="CASCADE"), primary_key=True),
        sa.Column("land_area_m2", sa.Numeric(12, 2)),
        sa.Column("fenced_area_m2", sa.Numeric(12, 2)),
        sa.Column("process_area_m2", sa.Numeric(10, 2)),
        sa.Column("terrain_type", sa.String(30)),
        sa.Column("ground_bearing_capacity_kpa", sa.Numeric(8, 2)),
        sa.Column("flood_risk", sa.String(10)),
        sa.Column("access_road_type", sa.String(30)),
        sa.Column("access_road_length_km", sa.Numeric(8, 3)),
        sa.Column("max_truck_tonnage_tonnes", sa.Numeric(6, 2)),
        sa.Column("power_supply_type", sa.String(30)),
        sa.Column("power_supply_kva", sa.Numeric(8, 2)),
        sa.Column("water_supply_type", sa.String(30)),
        sa.Column("water_storage_m3", sa.Numeric(8, 2)),
        sa.Column("internet_connectivity", sa.String(30)),
        sa.Column("has_control_room", sa.Boolean, server_default="false"),
        sa.Column("has_workshop", sa.Boolean, server_default="false"),
        sa.Column("has_warehouse", sa.Boolean, server_default="false"),
        sa.Column("has_accommodation", sa.Boolean, server_default="false"),
        sa.Column("accommodation_beds", sa.Integer),
        sa.Column("has_medical_room", sa.Boolean, server_default="false"),
        sa.Column("layout_drawing_ref", sa.String(100)),
        sa.Column("bunding_provided", sa.Boolean, server_default="false"),
        sa.Column("total_bunding_volume_m3", sa.Numeric(10, 2)),
        sa.Column("wind_rose_dominant_dir", sa.String(10)),
        sa.Column("environmental_permit_ref", sa.String(100)),
        sa.Column("operating_permit_ref", sa.String(100)),
        sa.Column("land_title_ref", sa.String(100)),
    )

    op.create_table(
        "ar_installation_decks",
        sa.Column("id", postgresql.UUID(as_uuid=True), server_default=sa.text("gen_random_uuid()"), primary_key=True),
        sa.Column("installation_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("ar_installations.id", ondelete="CASCADE"), nullable=False),
        sa.Column("deck_name", sa.String(50), nullable=False),
        sa.Column("deck_code", sa.String(10)),
        sa.Column("deck_order", sa.Integer, nullable=False),
        sa.Column("elevation_m", sa.Numeric(7, 2), nullable=False),
        sa.Column("deck_length_m", sa.Numeric(7, 2)),
        sa.Column("deck_width_m", sa.Numeric(7, 2)),
        sa.Column("deck_area_m2", sa.Numeric(9, 2)),
        sa.Column("max_deck_load_tm2", sa.Numeric(6, 2)),
        sa.Column("deck_function", sa.String(100)),
        sa.Column("notes", sa.Text),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.UniqueConstraint("installation_id", "deck_code", name="uq_ar_installation_decks_code"),
    )
    op.create_index("idx_ar_installation_decks_inst", "ar_installation_decks", ["installation_id"])
    op.execute("ALTER TABLE ar_installation_decks ADD COLUMN geom_footprint geography(POLYGON, 4326)")

    # ── EQUIPMENT (base) ───────────────────────────────────────

    op.create_table(
        "ar_equipment",
        sa.Column("id", postgresql.UUID(as_uuid=True), server_default=sa.text("gen_random_uuid()"), primary_key=True),
        sa.Column("entity_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("entities.id"), nullable=False),
        sa.Column("tag_number", sa.String(50), nullable=False),
        sa.Column("name", sa.String(200), nullable=False),
        sa.Column("equipment_class", sa.String(50), nullable=False),
        sa.Column("installation_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("ar_installations.id")),
        sa.Column("deck_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("ar_installation_decks.id")),
        sa.Column("area", sa.String(100)),
        sa.Column("sub_area", sa.String(100)),
        sa.Column("grid_reference", sa.String(20)),
        sa.Column("latitude", sa.Numeric(12, 8)),
        sa.Column("longitude", sa.Numeric(12, 8)),
        sa.Column("elevation_m", sa.Numeric(8, 2)),
        sa.Column("local_x_m", sa.Numeric(8, 2)),
        sa.Column("local_y_m", sa.Numeric(8, 2)),
        sa.Column("local_z_m", sa.Numeric(8, 2)),
        sa.Column("orientation_deg", sa.Numeric(6, 2)),
        sa.Column("is_mobile", sa.Boolean, server_default="false", nullable=False),
        sa.Column("manufacturer", sa.String(100)),
        sa.Column("model", sa.String(100)),
        sa.Column("serial_number", sa.String(100)),
        sa.Column("year_manufactured", sa.Integer),
        sa.Column("year_installed", sa.Integer),
        sa.Column("status", sa.String(30), server_default="OPERATIONAL", nullable=False),
        sa.Column("criticality", sa.String(1)),
        sa.Column("safety_function", sa.Boolean, server_default="false", nullable=False),
        sa.Column("cert_number", sa.String(100)),
        sa.Column("cert_authority", sa.String(100)),
        sa.Column("datasheet_url", sa.String(500)),
        sa.Column("manual_url", sa.String(500)),
        sa.Column("cert_document_url", sa.String(500)),
        sa.Column("drawing_number", sa.String(100)),
        sa.Column("p_and_id_ref", sa.String(100)),
        sa.Column("owner_company", sa.String(100)),
        sa.Column("asset_number", sa.String(100)),
        sa.Column("purchase_date", sa.Date),
        sa.Column("purchase_cost_usd", sa.Numeric(15, 2)),
        sa.Column("replacement_cost_usd", sa.Numeric(15, 2)),
        sa.Column("notes", sa.Text),
        sa.Column("created_by", postgresql.UUID(as_uuid=True)),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column("deleted_at", sa.DateTime(timezone=True)),
        sa.UniqueConstraint("entity_id", "tag_number", name="uq_ar_equipment_entity_tag"),
    )
    op.create_index("idx_ar_equipment_entity", "ar_equipment", ["entity_id"])
    op.create_index("idx_ar_equipment_class", "ar_equipment", ["equipment_class"])
    op.create_index("idx_ar_equipment_install", "ar_equipment", ["installation_id"])
    op.create_index("idx_ar_equipment_status", "ar_equipment", ["status"])
    op.execute("ALTER TABLE ar_equipment ADD COLUMN geom_point geography(POINT, 4326)")
    op.execute("CREATE INDEX idx_ar_equipment_geom ON ar_equipment USING GIST(geom_point)")

    # ── EQUIPMENT sub-tables ───────────────────────────────────

    op.create_table(
        "ar_equipment_documents",
        sa.Column("id", postgresql.UUID(as_uuid=True), server_default=sa.text("gen_random_uuid()"), primary_key=True),
        sa.Column("equipment_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("ar_equipment.id", ondelete="CASCADE"), nullable=False),
        sa.Column("document_type", sa.String(30)),
        sa.Column("document_title", sa.String(200)),
        sa.Column("document_number", sa.String(100)),
        sa.Column("revision", sa.String(10)),
        sa.Column("file_url", sa.String(500)),
        sa.Column("issued_by", sa.String(100)),
        sa.Column("issue_date", sa.Date),
        sa.Column("notes", sa.Text),
    )

    op.create_table(
        "ar_equipment_assignments",
        sa.Column("id", postgresql.UUID(as_uuid=True), server_default=sa.text("gen_random_uuid()"), primary_key=True),
        sa.Column("equipment_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("ar_equipment.id"), nullable=False),
        sa.Column("installation_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("ar_installations.id"), nullable=False),
        sa.Column("assigned_from", sa.Date, nullable=False),
        sa.Column("assigned_to", sa.Date),
        sa.Column("assignment_reason", sa.Text),
        sa.Column("work_order_ref", sa.String(100)),
        sa.Column("notes", sa.Text),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )

    # ── CRANE ──────────────────────────────────────────────────

    op.create_table(
        "ar_cranes",
        sa.Column("id", postgresql.UUID(as_uuid=True), sa.ForeignKey("ar_equipment.id", ondelete="CASCADE"), primary_key=True),
        sa.Column("crane_type", sa.String(50), nullable=False),
        sa.Column("boom_structure", sa.String(30)),
        sa.Column("mobility", sa.String(30)),
        sa.Column("is_offshore_rated", sa.Boolean, server_default="false", nullable=False),
        sa.Column("swl_tonnes", sa.Numeric(8, 2), nullable=False),
        sa.Column("max_capacity_tonnes", sa.Numeric(8, 2)),
        sa.Column("boom_min_length_m", sa.Numeric(6, 2)),
        sa.Column("boom_max_length_m", sa.Numeric(6, 2)),
        sa.Column("boom_min_angle_deg", sa.Numeric(5, 2)),
        sa.Column("boom_max_angle_deg", sa.Numeric(5, 2)),
        sa.Column("radius_min_m", sa.Numeric(6, 2)),
        sa.Column("radius_max_m", sa.Numeric(6, 2)),
        sa.Column("max_hook_height_m", sa.Numeric(6, 2)),
        sa.Column("has_jib", sa.Boolean, server_default="false", nullable=False),
        sa.Column("jib_max_length_m", sa.Numeric(6, 2)),
        sa.Column("jib_offset_deg", sa.Numeric(5, 2)),
        sa.Column("slewing_full_rotation", sa.Boolean, server_default="true", nullable=False),
        sa.Column("slewing_arc_deg", sa.Numeric(7, 2)),
        sa.Column("slewing_speed_rpm", sa.Numeric(6, 3)),
        sa.Column("hoist_speed_rated_mpm", sa.Numeric(6, 2)),
        sa.Column("hoist_speed_empty_mpm", sa.Numeric(6, 2)),
        sa.Column("lowering_speed_mpm", sa.Numeric(6, 2)),
        sa.Column("gross_weight_kg", sa.Numeric(10, 2)),
        sa.Column("counterweight_kg", sa.Numeric(10, 2)),
        sa.Column("hook_block_weight_kg", sa.Numeric(6, 2)),
        sa.Column("wire_rope_diameter_mm", sa.Numeric(5, 2)),
        sa.Column("wire_rope_length_m", sa.Numeric(7, 2)),
        sa.Column("wire_rope_grade", sa.String(30)),
        sa.Column("wire_rope_mbl_kn", sa.Numeric(8, 2)),
        sa.Column("reeving_main_max", sa.Integer),
        sa.Column("pedestal_diameter_mm", sa.Numeric(7, 2)),
        sa.Column("pedestal_height_m", sa.Numeric(6, 2)),
        sa.Column("base_bolt_circle_mm", sa.Numeric(7, 2)),
        sa.Column("base_bolt_count", sa.Integer),
        sa.Column("base_bolt_size", sa.String(10)),
        sa.Column("carrier_axles", sa.Integer),
        sa.Column("outrigger_spread_m", sa.Numeric(6, 2)),
        sa.Column("span_m", sa.Numeric(7, 2)),
        sa.Column("runway_length_m", sa.Numeric(8, 2)),
        sa.Column("max_wind_speed_op_ms", sa.Numeric(5, 2)),
        sa.Column("max_wind_speed_survival_ms", sa.Numeric(5, 2)),
        sa.Column("max_wave_height_op_m", sa.Numeric(5, 2)),
        sa.Column("max_heel_deg", sa.Numeric(4, 2)),
        sa.Column("max_trim_deg", sa.Numeric(4, 2)),
        sa.Column("power_supply_voltage_v", sa.Numeric(7, 2)),
        sa.Column("installed_power_kw", sa.Numeric(8, 2)),
        sa.Column("hydraulic_pressure_bar", sa.Numeric(7, 2)),
        sa.Column("lifting_moment_knm", sa.Numeric(10, 2)),
        sa.Column("lifting_moment_mt", sa.Numeric(10, 2)),
        sa.Column("design_standard", sa.String(50)),
        sa.Column("operation_standard", sa.String(50)),
        sa.Column("load_chart_reference", sa.String(100)),
        sa.Column("load_chart_unit", sa.String(10), server_default="TONNES", nullable=False),
        sa.Column("requires_operator_cert", sa.Boolean, server_default="true", nullable=False),
        sa.Column("operator_cert_standard", sa.String(50)),
        sa.Column("thorough_exam_interval_months", sa.Integer, server_default="6"),
    )

    op.create_table(
        "ar_crane_configurations",
        sa.Column("id", postgresql.UUID(as_uuid=True), server_default=sa.text("gen_random_uuid()"), primary_key=True),
        sa.Column("crane_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("ar_cranes.id", ondelete="CASCADE"), nullable=False),
        sa.Column("config_code", sa.String(30), nullable=False),
        sa.Column("config_name", sa.String(200)),
        sa.Column("is_default_config", sa.Boolean, server_default="false", nullable=False),
        sa.Column("config_order", sa.Integer),
        sa.Column("boom_length_m", sa.Numeric(6, 2), nullable=False),
        sa.Column("boom_length_ft", sa.Numeric(7, 2)),
        sa.Column("jib_installed", sa.Boolean, server_default="false", nullable=False),
        sa.Column("jib_length_m", sa.Numeric(6, 2)),
        sa.Column("jib_offset_deg", sa.Numeric(5, 2)),
        sa.Column("jib_type", sa.String(20)),
        sa.Column("counterweight_tonnes", sa.Numeric(8, 2)),
        sa.Column("outrigger_state", sa.String(20), server_default="NOT_APPLICABLE"),
        sa.Column("outrigger_length_m", sa.Numeric(6, 2)),
        sa.Column("reeving_parts", sa.Integer, server_default="1", nullable=False),
        sa.Column("reeving_line_pull_kn", sa.Numeric(8, 2)),
        sa.Column("hook_block_weight_kg", sa.Numeric(6, 2)),
        sa.Column("slewing_zone_description", sa.String(100)),
        sa.Column("blind_zone_start_deg", sa.Numeric(6, 2)),
        sa.Column("blind_zone_end_deg", sa.Numeric(6, 2)),
        sa.Column("config_max_capacity_tonnes", sa.Numeric(8, 2)),
        sa.Column("config_max_radius_m", sa.Numeric(6, 2)),
        sa.Column("notes", sa.Text),
        sa.UniqueConstraint("crane_id", "config_code", name="uq_ar_crane_config_code"),
    )

    op.create_table(
        "ar_crane_load_chart_points",
        sa.Column("id", postgresql.UUID(as_uuid=True), server_default=sa.text("gen_random_uuid()"), primary_key=True),
        sa.Column("config_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("ar_crane_configurations.id", ondelete="CASCADE"), nullable=False),
        sa.Column("radius_m", sa.Numeric(7, 3), nullable=False),
        sa.Column("max_load_tonnes", sa.Numeric(8, 3), nullable=False),
        sa.Column("hook_height_m", sa.Numeric(7, 2)),
        sa.Column("boom_angle_deg", sa.Numeric(6, 2)),
        sa.Column("load_raw", sa.Numeric(12, 3)),
        sa.Column("load_unit_source", sa.String(10)),
        sa.Column("hook_type", sa.String(15), server_default="MAIN_HOOK", nullable=False),
        sa.Column("row_order", sa.Integer),
        sa.Column("is_derated", sa.Boolean, server_default="false", nullable=False),
        sa.UniqueConstraint("config_id", "radius_m", "hook_type", name="uq_ar_crane_lcp"),
    )
    op.create_index("idx_ar_crane_lcp_config", "ar_crane_load_chart_points", ["config_id", "radius_m"])

    op.create_table(
        "ar_crane_lift_zones",
        sa.Column("id", postgresql.UUID(as_uuid=True), server_default=sa.text("gen_random_uuid()"), primary_key=True),
        sa.Column("config_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("ar_crane_configurations.id", ondelete="CASCADE"), nullable=False),
        sa.Column("zone_name", sa.String(100), nullable=False),
        sa.Column("angle_start_deg", sa.Numeric(6, 2), nullable=False),
        sa.Column("angle_end_deg", sa.Numeric(6, 2), nullable=False),
        sa.Column("angle_reference", sa.String(20), server_default="BOW", nullable=False),
        sa.Column("derating_factor", sa.Numeric(5, 4), server_default="1.0", nullable=False),
        sa.Column("derating_reason", sa.String(200)),
        sa.Column("max_load_override_tonnes", sa.Numeric(8, 2)),
        sa.Column("max_radius_override_m", sa.Numeric(6, 2)),
        sa.Column("notes", sa.Text),
    )

    op.create_table(
        "ar_crane_hook_blocks",
        sa.Column("id", postgresql.UUID(as_uuid=True), server_default=sa.text("gen_random_uuid()"), primary_key=True),
        sa.Column("crane_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("ar_cranes.id", ondelete="CASCADE"), nullable=False),
        sa.Column("block_reference", sa.String(100)),
        sa.Column("block_tag", sa.String(50)),
        sa.Column("sheave_count", sa.Integer),
        sa.Column("swivel_type", sa.String(30)),
        sa.Column("rated_capacity_tonnes", sa.Numeric(8, 2), nullable=False),
        sa.Column("compatible_reeving_max", sa.Integer),
        sa.Column("block_weight_kg", sa.Numeric(8, 2), nullable=False),
        sa.Column("hook_weight_kg", sa.Numeric(7, 2)),
        sa.Column("rope_diameter_mm", sa.Numeric(5, 2)),
        sa.Column("certificate_number", sa.String(100)),
        sa.Column("is_main_hook", sa.Boolean, server_default="true", nullable=False),
        sa.Column("is_current_fit", sa.Boolean, server_default="true", nullable=False),
    )

    op.create_table(
        "ar_crane_reeving_guide",
        sa.Column("id", postgresql.UUID(as_uuid=True), server_default=sa.text("gen_random_uuid()"), primary_key=True),
        sa.Column("crane_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("ar_cranes.id", ondelete="CASCADE"), nullable=False),
        sa.Column("boom_config_ref", sa.String(100)),
        sa.Column("load_min_tonnes", sa.Numeric(8, 3), nullable=False),
        sa.Column("load_max_tonnes", sa.Numeric(8, 3), nullable=False),
        sa.Column("reeving_parts", sa.Integer, nullable=False),
        sa.Column("config_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("ar_crane_configurations.id")),
        sa.UniqueConstraint("crane_id", "reeving_parts", name="uq_ar_crane_reeving"),
    )

    # ── SEPARATOR ──────────────────────────────────────────────

    op.create_table(
        "ar_separators",
        sa.Column("id", postgresql.UUID(as_uuid=True), sa.ForeignKey("ar_equipment.id", ondelete="CASCADE"), primary_key=True),
        sa.Column("separator_type", sa.String(30), nullable=False),
        sa.Column("orientation", sa.String(20), nullable=False),
        sa.Column("separation_stage", sa.Integer),
        sa.Column("train_id", sa.String(10)),
        sa.Column("is_test_separator", sa.Boolean, server_default="false", nullable=False),
        sa.Column("shell_id_mm", sa.Numeric(9, 2), nullable=False),
        sa.Column("shell_od_mm", sa.Numeric(9, 2)),
        sa.Column("tan_to_tan_mm", sa.Numeric(10, 2), nullable=False),
        sa.Column("overall_length_mm", sa.Numeric(10, 2)),
        sa.Column("head_type", sa.String(30)),
        sa.Column("total_volume_m3", sa.Numeric(9, 4)),
        sa.Column("liquid_volume_m3", sa.Numeric(9, 4)),
        sa.Column("gas_volume_m3", sa.Numeric(9, 4)),
        sa.Column("weight_empty_kg", sa.Numeric(10, 2)),
        sa.Column("weight_operating_kg", sa.Numeric(10, 2)),
        sa.Column("weight_hydrotest_kg", sa.Numeric(10, 2)),
        sa.Column("design_pressure_barg", sa.Numeric(9, 3), nullable=False),
        sa.Column("mawp_barg", sa.Numeric(9, 3)),
        sa.Column("design_temp_max_c", sa.Numeric(7, 2), nullable=False),
        sa.Column("design_temp_min_c", sa.Numeric(7, 2)),
        sa.Column("mdmt_c", sa.Numeric(7, 2)),
        sa.Column("hydro_test_pressure_barg", sa.Numeric(9, 3)),
        sa.Column("op_pressure_barg", sa.Numeric(9, 3)),
        sa.Column("op_temp_c", sa.Numeric(7, 2)),
        sa.Column("shell_material", sa.String(100)),
        sa.Column("design_code", sa.String(50), nullable=False),
        sa.Column("corrosion_allowance_mm", sa.Numeric(6, 2), nullable=False),
        sa.Column("wall_thickness_nominal_mm", sa.Numeric(6, 2)),
        sa.Column("pwht_required", sa.Boolean, server_default="false", nullable=False),
        sa.Column("u_stamp", sa.Boolean, server_default="false", nullable=False),
        sa.Column("support_type", sa.String(20)),
        sa.Column("skirt_height_m", sa.Numeric(6, 2)),
        sa.Column("inlet_device", sa.String(30)),
        sa.Column("mist_eliminator_type", sa.String(20), server_default="MESH_PAD"),
        sa.Column("weir_plate_installed", sa.Boolean, server_default="false", nullable=False),
        sa.Column("sand_jetting_system", sa.Boolean, server_default="false", nullable=False),
        sa.Column("fluid_service", sa.String(100)),
        sa.Column("h2s_ppm", sa.Numeric(10, 3)),
        sa.Column("co2_mol_pct", sa.Numeric(7, 4)),
        sa.Column("is_sour_service", sa.Boolean, server_default="false", nullable=False),
        sa.Column("nace_mr0175_applicable", sa.Boolean, server_default="false", nullable=False),
        sa.Column("gas_flow_mmscfd", sa.Numeric(10, 4)),
        sa.Column("oil_flow_sm3d", sa.Numeric(10, 3)),
        sa.Column("water_flow_sm3d", sa.Numeric(10, 3)),
        sa.Column("psv_count", sa.Integer, server_default="1"),
        sa.Column("primary_psv_tag", sa.String(50)),
        sa.Column("primary_psv_set_barg", sa.Numeric(9, 3)),
        sa.Column("bdv_tag", sa.String(50)),
        sa.Column("internal_inspection_interval_y", sa.Integer),
        sa.Column("notes", sa.Text),
    )

    op.create_table(
        "ar_separator_nozzles",
        sa.Column("id", postgresql.UUID(as_uuid=True), server_default=sa.text("gen_random_uuid()"), primary_key=True),
        sa.Column("separator_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("ar_separators.id", ondelete="CASCADE"), nullable=False),
        sa.Column("nozzle_mark", sa.String(10), nullable=False),
        sa.Column("nozzle_service", sa.String(30), nullable=False),
        sa.Column("description", sa.String(200)),
        sa.Column("nominal_size_in", sa.Numeric(6, 2), nullable=False),
        sa.Column("schedule", sa.String(20)),
        sa.Column("connection_type", sa.String(20)),
        sa.Column("flange_rating", sa.String(10)),
        sa.Column("nozzle_material", sa.String(100)),
        sa.Column("connected_to_tag", sa.String(50)),
        sa.UniqueConstraint("separator_id", "nozzle_mark", name="uq_ar_sep_nozzle_mark"),
    )

    op.create_table(
        "ar_separator_process_cases",
        sa.Column("id", postgresql.UUID(as_uuid=True), server_default=sa.text("gen_random_uuid()"), primary_key=True),
        sa.Column("separator_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("ar_separators.id", ondelete="CASCADE"), nullable=False),
        sa.Column("case_name", sa.String(20), nullable=False),
        sa.Column("case_description", sa.String(200)),
        sa.Column("inlet_pressure_barg", sa.Numeric(9, 3)),
        sa.Column("inlet_temp_c", sa.Numeric(7, 2)),
        sa.Column("inlet_gas_flow_mmscfd", sa.Numeric(10, 4)),
        sa.Column("inlet_oil_flow_sm3d", sa.Numeric(10, 3)),
        sa.Column("inlet_water_flow_sm3d", sa.Numeric(10, 3)),
        sa.Column("op_pressure_barg", sa.Numeric(9, 3)),
        sa.Column("op_temp_c", sa.Numeric(7, 2)),
        sa.Column("simulation_tool", sa.String(30)),
        sa.Column("simulation_case_ref", sa.String(100)),
        sa.UniqueConstraint("separator_id", "case_name", name="uq_ar_sep_case_name"),
    )

    # ── OTHER SPECIALIZED EQUIPMENT ────────────────────────────

    # Pump
    op.create_table(
        "ar_pumps",
        sa.Column("id", postgresql.UUID(as_uuid=True), sa.ForeignKey("ar_equipment.id", ondelete="CASCADE"), primary_key=True),
        sa.Column("pump_type", sa.String(30), nullable=False),
        sa.Column("pump_service", sa.String(100)),
        sa.Column("number_of_stages", sa.Integer, server_default="1", nullable=False),
        sa.Column("orientation", sa.String(20)),
        sa.Column("duty_standby", sa.String(10)),
        sa.Column("paired_pump_tag", sa.String(50)),
        sa.Column("fluid_description", sa.String(200)),
        sa.Column("fluid_density_kgm3", sa.Numeric(8, 3), nullable=False),
        sa.Column("h2s_ppm", sa.Numeric(8, 2)),
        sa.Column("is_sour_service", sa.Boolean, server_default="false", nullable=False),
        sa.Column("flow_rated_m3h", sa.Numeric(10, 3), nullable=False),
        sa.Column("flow_min_m3h", sa.Numeric(10, 3)),
        sa.Column("flow_max_m3h", sa.Numeric(10, 3)),
        sa.Column("head_rated_m", sa.Numeric(9, 2), nullable=False),
        sa.Column("differential_pressure_barg", sa.Numeric(9, 3)),
        sa.Column("suction_pressure_barg", sa.Numeric(9, 3)),
        sa.Column("discharge_pressure_barg", sa.Numeric(9, 3)),
        sa.Column("npsha_m", sa.Numeric(8, 3)),
        sa.Column("npshr_m", sa.Numeric(8, 3)),
        sa.Column("efficiency_rated_pct", sa.Numeric(5, 2)),
        sa.Column("design_pressure_barg", sa.Numeric(9, 3)),
        sa.Column("design_temp_max_c", sa.Numeric(7, 2)),
        sa.Column("motor_rated_power_kw", sa.Numeric(8, 2), nullable=False),
        sa.Column("motor_voltage_v", sa.Numeric(8, 2)),
        sa.Column("motor_speed_rpm", sa.Numeric(7, 2)),
        sa.Column("vfd_installed", sa.Boolean, server_default="false", nullable=False),
        sa.Column("pump_speed_rpm", sa.Numeric(7, 2)),
        sa.Column("impeller_diameter_mm", sa.Numeric(7, 2)),
        sa.Column("impeller_material", sa.String(100)),
        sa.Column("casing_material", sa.String(100)),
        sa.Column("seal_type", sa.String(30)),
        sa.Column("design_code", sa.String(30)),
        sa.Column("overhaul_interval_h", sa.Integer),
    )

    op.create_table(
        "ar_pump_curve_points",
        sa.Column("id", postgresql.UUID(as_uuid=True), server_default=sa.text("gen_random_uuid()"), primary_key=True),
        sa.Column("pump_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("ar_pumps.id", ondelete="CASCADE"), nullable=False),
        sa.Column("flow_m3h", sa.Numeric(10, 3), nullable=False),
        sa.Column("head_m", sa.Numeric(9, 2)),
        sa.Column("efficiency_pct", sa.Numeric(5, 2)),
        sa.Column("power_kw", sa.Numeric(8, 2)),
        sa.Column("npshr_m", sa.Numeric(8, 3)),
        sa.Column("speed_rpm", sa.Numeric(7, 2)),
        sa.Column("source", sa.String(20), server_default="MANUFACTURER", nullable=False),
        sa.UniqueConstraint("pump_id", "flow_m3h", "speed_rpm", name="uq_ar_pump_curve"),
    )

    # Gas Compressor
    op.create_table(
        "ar_gas_compressors",
        sa.Column("id", postgresql.UUID(as_uuid=True), sa.ForeignKey("ar_equipment.id", ondelete="CASCADE"), primary_key=True),
        sa.Column("compressor_type", sa.String(20), nullable=False),
        sa.Column("service", sa.String(30), nullable=False),
        sa.Column("number_of_stages", sa.Integer, server_default="1", nullable=False),
        sa.Column("gas_description", sa.String(200)),
        sa.Column("mole_weight_kgkmol", sa.Numeric(7, 3)),
        sa.Column("h2s_ppm", sa.Numeric(8, 2)),
        sa.Column("co2_mol_pct", sa.Numeric(6, 3)),
        sa.Column("gas_composition_json", postgresql.JSONB),
        sa.Column("flow_mmscfd", sa.Numeric(10, 4)),
        sa.Column("suction_pressure_barg", sa.Numeric(9, 3), nullable=False),
        sa.Column("discharge_pressure_barg", sa.Numeric(9, 3), nullable=False),
        sa.Column("compression_ratio", sa.Numeric(7, 4)),
        sa.Column("suction_temp_c", sa.Numeric(7, 2)),
        sa.Column("discharge_temp_c", sa.Numeric(7, 2)),
        sa.Column("polytropic_efficiency_pct", sa.Numeric(5, 2)),
        sa.Column("shaft_power_kw", sa.Numeric(10, 2)),
        sa.Column("driver_type", sa.String(20)),
        sa.Column("driver_tag", sa.String(50)),
        sa.Column("driver_rated_power_kw", sa.Numeric(10, 2)),
        sa.Column("compressor_speed_rpm", sa.Numeric(7, 2)),
        sa.Column("number_of_impellers", sa.Integer),
        sa.Column("surge_margin_pct", sa.Numeric(5, 2)),
        sa.Column("anti_surge_valve_tag", sa.String(50)),
        sa.Column("dgs_installed", sa.Boolean, server_default="false", nullable=False),
        sa.Column("design_code", sa.String(20)),
        sa.Column("overhaul_interval_h", sa.Integer),
    )

    # Gas Turbine
    op.create_table(
        "ar_gas_turbines",
        sa.Column("id", postgresql.UUID(as_uuid=True), sa.ForeignKey("ar_equipment.id", ondelete="CASCADE"), primary_key=True),
        sa.Column("application", sa.String(20), nullable=False),
        sa.Column("turbine_class", sa.String(20)),
        sa.Column("number_of_shafts", sa.Integer, server_default="1", nullable=False),
        sa.Column("model_designation", sa.String(100)),
        sa.Column("iso_power_kw", sa.Numeric(12, 2), nullable=False),
        sa.Column("iso_heat_rate_kjkwh", sa.Numeric(10, 2)),
        sa.Column("iso_thermal_efficiency_pct", sa.Numeric(5, 2)),
        sa.Column("site_power_kw", sa.Numeric(12, 2)),
        sa.Column("site_ambient_temp_design_c", sa.Numeric(6, 2)),
        sa.Column("primary_fuel_type", sa.String(30)),
        sa.Column("dual_fuel", sa.Boolean, server_default="false", nullable=False),
        sa.Column("pressure_ratio", sa.Numeric(7, 4), nullable=False),
        sa.Column("output_voltage_v", sa.Numeric(8, 2)),
        sa.Column("output_frequency_hz", sa.Numeric(5, 2), server_default="50"),
        sa.Column("output_rated_power_kw", sa.Numeric(12, 2)),
        sa.Column("driven_equipment_tag", sa.String(50)),
        sa.Column("combustion_inspection_eoh", sa.Integer),
        sa.Column("hot_section_inspection_eoh", sa.Integer),
        sa.Column("major_overhaul_eoh", sa.Integer),
        sa.Column("oem_ltsa_contract", sa.Boolean, server_default="false", nullable=False),
        sa.Column("design_code", sa.String(30)),
    )

    # Diesel Generator
    op.create_table(
        "ar_diesel_generators",
        sa.Column("id", postgresql.UUID(as_uuid=True), sa.ForeignKey("ar_equipment.id", ondelete="CASCADE"), primary_key=True),
        sa.Column("is_emergency_generator", sa.Boolean, server_default="false", nullable=False),
        sa.Column("generator_class", sa.String(5)),
        sa.Column("engine_manufacturer", sa.String(100), nullable=False),
        sa.Column("engine_model", sa.String(100), nullable=False),
        sa.Column("engine_speed_rpm", sa.Numeric(7, 2)),
        sa.Column("engine_cylinders", sa.Integer),
        sa.Column("rated_power_kw", sa.Numeric(10, 2), nullable=False),
        sa.Column("standby_power_kw", sa.Numeric(10, 2)),
        sa.Column("voltage_v", sa.Numeric(8, 2), nullable=False),
        sa.Column("frequency_hz", sa.Numeric(5, 2), server_default="50"),
        sa.Column("power_factor", sa.Numeric(4, 3), server_default="0.8"),
        sa.Column("fuel_type", sa.String(20), server_default="HSD"),
        sa.Column("fuel_consumption_at_100_lph", sa.Numeric(8, 3)),
        sa.Column("base_tank_capacity_l", sa.Numeric(10, 2)),
        sa.Column("fuel_autonomy_at_full_load_h", sa.Numeric(7, 2)),
        sa.Column("auto_start_on_mains_failure", sa.Boolean, server_default="true", nullable=False),
        sa.Column("parallel_operation", sa.Boolean, server_default="false", nullable=False),
        sa.Column("design_code", sa.String(50)),
    )

    # Storage Tank
    op.create_table(
        "ar_storage_tanks",
        sa.Column("id", postgresql.UUID(as_uuid=True), sa.ForeignKey("ar_equipment.id", ondelete="CASCADE"), primary_key=True),
        sa.Column("tank_type", sa.String(30), nullable=False),
        sa.Column("tank_service", sa.String(100)),
        sa.Column("api_standard", sa.String(10)),
        sa.Column("nominal_capacity_m3", sa.Numeric(12, 3), nullable=False),
        sa.Column("usable_capacity_m3", sa.Numeric(12, 3)),
        sa.Column("shell_diameter_m", sa.Numeric(9, 3), nullable=False),
        sa.Column("shell_height_m", sa.Numeric(8, 3), nullable=False),
        sa.Column("shell_courses", sa.Integer),
        sa.Column("design_pressure_mbarg", sa.Numeric(8, 3), server_default="0"),
        sa.Column("design_temp_max_c", sa.Numeric(7, 2)),
        sa.Column("specific_gravity_product", sa.Numeric(5, 4)),
        sa.Column("shell_material", sa.String(100)),
        sa.Column("internal_coating", sa.String(100)),
        sa.Column("external_coating", sa.String(100)),
        sa.Column("foundation_type", sa.String(20)),
        sa.Column("bund_provided", sa.Boolean, server_default="true", nullable=False),
        sa.Column("bund_capacity_m3", sa.Numeric(12, 3)),
        sa.Column("gesip_compliant", sa.Boolean, server_default="false", nullable=False),
        sa.Column("foam_system_type", sa.String(20)),
        sa.Column("internal_inspection_interval_y", sa.Integer, server_default="10"),
    )

    # Heat Exchanger
    op.create_table(
        "ar_heat_exchangers",
        sa.Column("id", postgresql.UUID(as_uuid=True), sa.ForeignKey("ar_equipment.id", ondelete="CASCADE"), primary_key=True),
        sa.Column("hx_type", sa.String(20), nullable=False),
        sa.Column("service_description", sa.String(200)),
        sa.Column("tema_type", sa.String(10)),
        sa.Column("tema_class", sa.String(5)),
        sa.Column("shell_fluid", sa.String(100)),
        sa.Column("shell_design_pressure_barg", sa.Numeric(9, 3)),
        sa.Column("shell_design_temp_max_c", sa.Numeric(7, 2)),
        sa.Column("shell_material", sa.String(100)),
        sa.Column("tube_fluid", sa.String(100)),
        sa.Column("tube_design_pressure_barg", sa.Numeric(9, 3)),
        sa.Column("tube_material", sa.String(100)),
        sa.Column("tube_count", sa.Integer),
        sa.Column("tube_length_m", sa.Numeric(7, 2)),
        sa.Column("number_of_passes", sa.Integer, server_default="1"),
        sa.Column("duty_kw", sa.Numeric(10, 2)),
        sa.Column("heat_transfer_area_m2", sa.Numeric(9, 2)),
        sa.Column("design_code", sa.String(30)),
        sa.Column("total_weight_dry_kg", sa.Numeric(10, 2)),
    )

    # Pressure Vessel
    op.create_table(
        "ar_pressure_vessels",
        sa.Column("id", postgresql.UUID(as_uuid=True), sa.ForeignKey("ar_equipment.id", ondelete="CASCADE"), primary_key=True),
        sa.Column("vessel_type", sa.String(30), nullable=False),
        sa.Column("service_description", sa.String(200)),
        sa.Column("orientation", sa.String(20), nullable=False),
        sa.Column("shell_id_mm", sa.Numeric(9, 2), nullable=False),
        sa.Column("tan_to_tan_mm", sa.Numeric(10, 2)),
        sa.Column("total_volume_m3", sa.Numeric(9, 4)),
        sa.Column("weight_empty_kg", sa.Numeric(10, 2)),
        sa.Column("design_pressure_barg", sa.Numeric(9, 3), nullable=False),
        sa.Column("mawp_barg", sa.Numeric(9, 3)),
        sa.Column("design_temp_max_c", sa.Numeric(7, 2), nullable=False),
        sa.Column("design_temp_min_c", sa.Numeric(7, 2)),
        sa.Column("shell_material", sa.String(100)),
        sa.Column("design_code", sa.String(50)),
        sa.Column("corrosion_allowance_mm", sa.Numeric(5, 2)),
        sa.Column("psv_tag", sa.String(50)),
        sa.Column("psv_set_barg", sa.Numeric(8, 3)),
    )

    # Instrument
    op.create_table(
        "ar_instruments",
        sa.Column("id", postgresql.UUID(as_uuid=True), sa.ForeignKey("ar_equipment.id", ondelete="CASCADE"), primary_key=True),
        sa.Column("instrument_type", sa.String(10), nullable=False),
        sa.Column("loop_number", sa.String(50)),
        sa.Column("loop_description", sa.String(200)),
        sa.Column("parent_equipment_tag", sa.String(50)),
        sa.Column("p_and_id_ref", sa.String(100)),
        sa.Column("fluid_service", sa.String(100)),
        sa.Column("range_min", sa.Numeric(14, 5)),
        sa.Column("range_max", sa.Numeric(14, 5)),
        sa.Column("range_unit", sa.String(30)),
        sa.Column("signal_type", sa.String(20)),
        sa.Column("fail_safe_position", sa.String(5)),
        sa.Column("design_pressure_barg", sa.Numeric(9, 3)),
        sa.Column("design_temp_max_c", sa.Numeric(7, 2)),
        sa.Column("wetted_material", sa.String(100)),
        sa.Column("hazardous_area_zone", sa.String(10)),
        sa.Column("atex_certificate_number", sa.String(100)),
        sa.Column("ip_rating", sa.String(10)),
        sa.Column("calibration_interval_months", sa.Integer, server_default="12"),
        sa.Column("sil_rated", sa.Boolean, server_default="false", nullable=False),
        sa.Column("sil_level", sa.String(5)),
        sa.Column("valve_body_size_in", sa.Numeric(5, 2)),
        sa.Column("valve_body_material", sa.String(50)),
        sa.Column("valve_actuator_type", sa.String(20)),
        sa.Column("valve_cv_rated", sa.Numeric(8, 3)),
    )

    # Piping Line
    op.create_table(
        "ar_piping_lines",
        sa.Column("id", postgresql.UUID(as_uuid=True), sa.ForeignKey("ar_equipment.id", ondelete="CASCADE"), primary_key=True),
        sa.Column("line_number", sa.String(150), nullable=False),
        sa.Column("line_class", sa.String(20)),
        sa.Column("service_description", sa.String(200)),
        sa.Column("nominal_diameter_in", sa.Numeric(6, 2), nullable=False),
        sa.Column("schedule", sa.String(20)),
        sa.Column("pipe_material_spec", sa.String(100)),
        sa.Column("design_pressure_barg", sa.Numeric(9, 3), nullable=False),
        sa.Column("design_temp_max_c", sa.Numeric(7, 2), nullable=False),
        sa.Column("design_code", sa.String(20)),
    )
    op.execute("ALTER TABLE ar_piping_lines ADD COLUMN geom_route geography(LINESTRING, 4326)")

    # Wellhead
    op.create_table(
        "ar_wellheads",
        sa.Column("id", postgresql.UUID(as_uuid=True), sa.ForeignKey("ar_equipment.id", ondelete="CASCADE"), primary_key=True),
        sa.Column("well_tag", sa.String(50)),
        sa.Column("well_name", sa.String(100)),
        sa.Column("well_type", sa.String(15)),
        sa.Column("slot_number", sa.String(20)),
        sa.Column("wellhead_type", sa.String(30)),
        sa.Column("wp_class", sa.String(15)),
        sa.Column("design_pressure_psi", sa.Numeric(9, 2)),
        sa.Column("design_pressure_barg", sa.Numeric(9, 3)),
        sa.Column("h2s_service", sa.Boolean, server_default="false", nullable=False),
        sa.Column("xt_type", sa.String(20)),
        sa.Column("xt_manufacturer", sa.String(100)),
        sa.Column("xt_model", sa.String(100)),
        sa.Column("scssv_installed", sa.Boolean, server_default="true", nullable=False),
        sa.Column("scssv_type", sa.String(20)),
        sa.Column("scssv_depth_m", sa.Numeric(10, 2)),
    )

    # Flare System
    op.create_table(
        "ar_flare_systems",
        sa.Column("id", postgresql.UUID(as_uuid=True), sa.ForeignKey("ar_equipment.id", ondelete="CASCADE"), primary_key=True),
        sa.Column("flare_type", sa.String(30), nullable=False),
        sa.Column("service", sa.String(30)),
        sa.Column("design_standard", sa.String(30)),
        sa.Column("tip_manufacturer", sa.String(100)),
        sa.Column("tip_diameter_in", sa.Numeric(6, 2)),
        sa.Column("stack_height_m", sa.Numeric(8, 2)),
        sa.Column("smokeless_capacity_mmscfd", sa.Numeric(10, 4)),
        sa.Column("max_relief_capacity_mmscfd", sa.Numeric(10, 4)),
        sa.Column("ignition_type", sa.String(20)),
        sa.Column("pilot_count", sa.Integer),
        sa.Column("ko_drum_tag", sa.String(50)),
        sa.Column("seal_drum_tag", sa.String(50)),
        sa.Column("exclusion_zone_m", sa.Numeric(7, 2)),
    )

    # ESD System
    op.create_table(
        "ar_esd_systems",
        sa.Column("id", postgresql.UUID(as_uuid=True), sa.ForeignKey("ar_equipment.id", ondelete="CASCADE"), primary_key=True),
        sa.Column("system_name", sa.String(100)),
        sa.Column("system_type", sa.String(20)),
        sa.Column("sil_level", sa.String(5), nullable=False),
        sa.Column("iec_61511_compliant", sa.Boolean, server_default="true", nullable=False),
        sa.Column("logic_solver_manufacturer", sa.String(50)),
        sa.Column("logic_solver_model", sa.String(50)),
        sa.Column("voted_configuration", sa.String(10)),
        sa.Column("number_of_sifs", sa.Integer),
        sa.Column("number_of_esd_valves", sa.Integer),
        sa.Column("esd_levels", postgresql.JSONB),
        sa.Column("target_pfd", sa.Numeric(10, 8)),
        sa.Column("design_code", sa.String(30)),
    )

    # Fire Water System
    op.create_table(
        "ar_fire_water_systems",
        sa.Column("id", postgresql.UUID(as_uuid=True), sa.ForeignKey("ar_equipment.id", ondelete="CASCADE"), primary_key=True),
        sa.Column("system_type", sa.String(20)),
        sa.Column("service_area", sa.String(200)),
        sa.Column("design_standard", sa.String(30)),
        sa.Column("ring_main_size_in", sa.Numeric(5, 2)),
        sa.Column("main_pump_tag", sa.String(50)),
        sa.Column("main_pump_flow_m3h", sa.Numeric(8, 2)),
        sa.Column("tank_tag", sa.String(50)),
        sa.Column("tank_capacity_m3", sa.Numeric(8, 2)),
        sa.Column("autonomy_min", sa.Integer),
        sa.Column("deluge_zones", sa.Integer),
        sa.Column("foam_concentrate_type", sa.String(15)),
    )

    # Transformer
    op.create_table(
        "ar_transformers",
        sa.Column("id", postgresql.UUID(as_uuid=True), sa.ForeignKey("ar_equipment.id", ondelete="CASCADE"), primary_key=True),
        sa.Column("transformer_type", sa.String(25)),
        sa.Column("cooling_type", sa.String(15)),
        sa.Column("primary_voltage_v", sa.Numeric(9, 2), nullable=False),
        sa.Column("secondary_voltage_v", sa.Numeric(9, 2), nullable=False),
        sa.Column("rated_power_kva", sa.Numeric(10, 2), nullable=False),
        sa.Column("frequency_hz", sa.Numeric(5, 2), server_default="50"),
        sa.Column("vector_group", sa.String(10)),
        sa.Column("impedance_pct", sa.Numeric(5, 2)),
        sa.Column("oil_volume_l", sa.Numeric(8, 2)),
        sa.Column("design_code", sa.String(20)),
    )

    # Lifting Accessory
    op.create_table(
        "ar_lifting_accessories",
        sa.Column("id", postgresql.UUID(as_uuid=True), sa.ForeignKey("ar_equipment.id", ondelete="CASCADE"), primary_key=True),
        sa.Column("accessory_type", sa.String(25), nullable=False),
        sa.Column("is_part_of_set", sa.Boolean, server_default="false", nullable=False),
        sa.Column("set_reference", sa.String(50)),
        sa.Column("wll_tonnes", sa.Numeric(8, 3), nullable=False),
        sa.Column("swl_tonnes", sa.Numeric(8, 3)),
        sa.Column("safety_factor", sa.Numeric(5, 2), server_default="4.0"),
        sa.Column("number_of_legs", sa.Integer, server_default="1", nullable=False),
        sa.Column("nominal_size_mm", sa.Numeric(7, 2)),
        sa.Column("length_m", sa.Numeric(7, 3)),
        sa.Column("material", sa.String(50)),
        sa.Column("grade", sa.String(20)),
        sa.Column("self_weight_kg", sa.Numeric(8, 2)),
        sa.Column("colour_code", sa.String(20)),
        sa.Column("cert_standard", sa.String(30)),
        sa.Column("cert_number", sa.String(100)),
        sa.Column("examination_interval_months", sa.Integer, server_default="6"),
        sa.Column("storage_location", sa.String(100)),
    )

    # ── PIPELINE ───────────────────────────────────────────────

    op.create_table(
        "ar_pipelines",
        sa.Column("id", postgresql.UUID(as_uuid=True), server_default=sa.text("gen_random_uuid()"), primary_key=True),
        sa.Column("entity_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("entities.id"), nullable=False),
        sa.Column("pipeline_id", sa.String(50), nullable=False),
        sa.Column("name", sa.String(200), nullable=False),
        sa.Column("service", sa.String(50), nullable=False),
        sa.Column("status", sa.String(30), server_default="OPERATIONAL", nullable=False),
        sa.Column("from_installation_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("ar_installations.id"), nullable=False),
        sa.Column("to_installation_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("ar_installations.id"), nullable=False),
        sa.Column("from_node_description", sa.String(200)),
        sa.Column("to_node_description", sa.String(200)),
        sa.Column("total_length_km", sa.Numeric(10, 4)),
        sa.Column("onshore_length_km", sa.Numeric(10, 4)),
        sa.Column("offshore_length_km", sa.Numeric(10, 4)),
        sa.Column("nominal_diameter_in", sa.Numeric(6, 2), nullable=False),
        sa.Column("od_mm", sa.Numeric(8, 3)),
        sa.Column("wall_thickness_mm", sa.Numeric(6, 3)),
        sa.Column("pipe_material", sa.String(100)),
        sa.Column("pipe_grade", sa.String(30)),
        sa.Column("coating_external", sa.String(50)),
        sa.Column("coating_internal", sa.String(50)),
        sa.Column("design_pressure_barg", sa.Numeric(9, 3), nullable=False),
        sa.Column("design_temp_max_c", sa.Numeric(7, 2), nullable=False),
        sa.Column("design_temp_min_c", sa.Numeric(7, 2)),
        sa.Column("maop_barg", sa.Numeric(9, 3)),
        sa.Column("test_pressure_barg", sa.Numeric(9, 3)),
        sa.Column("max_water_depth_m", sa.Numeric(8, 2)),
        sa.Column("fluid_description", sa.String(100)),
        sa.Column("h2s_ppm", sa.Numeric(8, 2)),
        sa.Column("co2_mol_pct", sa.Numeric(6, 3)),
        sa.Column("cp_required", sa.Boolean, server_default="false", nullable=False),
        sa.Column("cp_type", sa.String(30)),
        sa.Column("piggable", sa.Boolean, server_default="false", nullable=False),
        sa.Column("pig_launcher_tag", sa.String(50)),
        sa.Column("pig_receiver_tag", sa.String(50)),
        sa.Column("design_code", sa.String(30)),
        sa.Column("design_life_years", sa.Integer),
        sa.Column("installation_year", sa.Integer),
        sa.Column("corrosion_allowance_mm", sa.Numeric(5, 2)),
        sa.Column("permit_number", sa.String(100)),
        sa.Column("regulator", sa.String(100)),
        sa.Column("notes", sa.Text),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column("deleted_at", sa.DateTime(timezone=True)),
        sa.UniqueConstraint("entity_id", "pipeline_id", name="uq_ar_pipelines_entity_pid"),
    )
    op.create_index("idx_ar_pipelines_entity", "ar_pipelines", ["entity_id"])
    op.create_index("idx_ar_pipelines_from", "ar_pipelines", ["from_installation_id"])
    op.create_index("idx_ar_pipelines_to", "ar_pipelines", ["to_installation_id"])
    op.execute("ALTER TABLE ar_pipelines ADD COLUMN geom_route geography(LINESTRING, 4326)")
    op.execute("CREATE INDEX idx_ar_pipelines_geom ON ar_pipelines USING GIST(geom_route)")

    op.create_table(
        "ar_pipeline_waypoints",
        sa.Column("id", postgresql.UUID(as_uuid=True), server_default=sa.text("gen_random_uuid()"), primary_key=True),
        sa.Column("pipeline_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("ar_pipelines.id", ondelete="CASCADE"), nullable=False),
        sa.Column("sequence_no", sa.Integer, nullable=False),
        sa.Column("latitude", sa.Numeric(12, 8), nullable=False),
        sa.Column("longitude", sa.Numeric(12, 8), nullable=False),
        sa.Column("elevation_m", sa.Numeric(8, 2)),
        sa.Column("chainage_km", sa.Numeric(10, 4)),
        sa.Column("environment", sa.String(30)),
        sa.Column("water_depth_m", sa.Numeric(8, 2)),
        sa.Column("burial_depth_m", sa.Numeric(5, 2)),
        sa.Column("waypoint_type", sa.String(20)),
        sa.Column("waypoint_name", sa.String(100)),
        sa.Column("notes", sa.Text),
        sa.UniqueConstraint("pipeline_id", "sequence_no", name="uq_ar_pipeline_waypoints_seq"),
    )
    op.create_index("idx_ar_pipeline_waypoints_pipe", "ar_pipeline_waypoints", ["pipeline_id", "sequence_no"])
    op.execute("ALTER TABLE ar_pipeline_waypoints ADD COLUMN geom_point geography(POINT, 4326)")

    # ── INSTALLATION CONNECTIONS ───────────────────────────────

    op.create_table(
        "ar_installation_connections",
        sa.Column("id", postgresql.UUID(as_uuid=True), server_default=sa.text("gen_random_uuid()"), primary_key=True),
        sa.Column("from_installation_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("ar_installations.id"), nullable=False),
        sa.Column("to_installation_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("ar_installations.id"), nullable=False),
        sa.Column("connection_type", sa.String(30)),
        sa.Column("tag_number", sa.String(50)),
        sa.Column("name", sa.String(200)),
        sa.Column("length_m", sa.Numeric(8, 2)),
        sa.Column("capacity", sa.String(100)),
        sa.Column("status", sa.String(30), server_default="OPERATIONAL", nullable=False),
        sa.Column("notes", sa.Text),
    )


def downgrade() -> None:
    # Drop in reverse order of creation
    tables = [
        "ar_installation_connections",
        "ar_pipeline_waypoints", "ar_pipelines",
        "ar_lifting_accessories", "ar_transformers",
        "ar_fire_water_systems", "ar_esd_systems", "ar_flare_systems",
        "ar_wellheads", "ar_piping_lines",
        "ar_instruments", "ar_pressure_vessels", "ar_heat_exchangers",
        "ar_storage_tanks", "ar_diesel_generators", "ar_gas_turbines",
        "ar_gas_compressors", "ar_pump_curve_points", "ar_pumps",
        "ar_separator_process_cases", "ar_separator_nozzles", "ar_separators",
        "ar_crane_reeving_guide", "ar_crane_hook_blocks",
        "ar_crane_lift_zones", "ar_crane_load_chart_points",
        "ar_crane_configurations", "ar_cranes",
        "ar_equipment_assignments", "ar_equipment_documents", "ar_equipment",
        "ar_installation_decks",
        "ar_installation_onshore_details", "ar_installation_offshore_details",
        "ar_installations", "ar_sites", "ar_fields",
    ]
    for t in tables:
        op.drop_table(t)
