/**
 * Map server-provided icon names to lucide-react-native components.
 *
 * The backend (form_definitions.py, portal configs) emits free-form icon
 * names like "scan", "qr-code", "package-plus" etc. We map them to lucide
 * icons here so screens can stay agnostic.
 */
import {
  Activity,
  Anchor,
  Archive,
  Bell,
  Boxes,
  Briefcase,
  Building2,
  Calendar,
  Car,
  CheckCircle,
  Clipboard,
  ClipboardCheck,
  Cog,
  CreditCard,
  Edit3,
  FileBadge,
  FileEdit,
  FilePlus,
  Folder,
  Gauge,
  Globe,
  HelpCircle,
  Home,
  Inbox,
  Key,
  Layers,
  LayoutDashboard,
  List,
  Mail,
  Map,
  MapPin,
  Navigation,
  Package,
  PackagePlus,
  PenSquare,
  Phone,
  Plane,
  PlusCircle,
  QrCode,
  ScanLine,
  Search,
  Settings,
  Shield,
  Ship,
  Smartphone,
  Star,
  Truck,
  User,
  UserPlus,
  Users,
  type LucideIcon,
} from "lucide-react-native";

const MAP: Record<string, LucideIcon> = {
  activity: Activity,
  anchor: Anchor,
  archive: Archive,
  bell: Bell,
  boxes: Boxes,
  briefcase: Briefcase,
  "building-2": Building2,
  building: Building2,
  calendar: Calendar,
  car: Car,
  "check-circle": CheckCircle,
  clipboard: Clipboard,
  "clipboard-check": ClipboardCheck,
  cog: Cog,
  "credit-card": CreditCard,
  "edit-3": Edit3,
  edit: Edit3,
  "file-badge": FileBadge,
  "file-edit": FileEdit,
  "file-plus": FilePlus,
  folder: Folder,
  gauge: Gauge,
  globe: Globe,
  "help-circle": HelpCircle,
  home: Home,
  inbox: Inbox,
  key: Key,
  layers: Layers,
  "layout-dashboard": LayoutDashboard,
  list: List,
  mail: Mail,
  map: Map,
  "map-pin": MapPin,
  navigation: Navigation,
  package: Package,
  "package-plus": PackagePlus,
  "pen-square": PenSquare,
  phone: Phone,
  plane: Plane,
  "plus-circle": PlusCircle,
  "qr-code": QrCode,
  scan: ScanLine,
  "scan-circle": ScanLine,
  "scan-line": ScanLine,
  search: Search,
  settings: Settings,
  shield: Shield,
  ship: Ship,
  smartphone: Smartphone,
  star: Star,
  truck: Truck,
  user: User,
  "user-plus": UserPlus,
  users: Users,
};

/** Return the lucide icon for a name. Falls back to List. */
export function iconByName(name?: string): LucideIcon {
  if (!name) return List;
  return MAP[name.toLowerCase()] ?? List;
}
