"""add_2fa_tables

Revision ID: a1b2c3d4e5f6
Revises: 5f3e8a9d2c1b
Create Date: 2025-01-12 23:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a1b2c3d4e5f6'
down_revision: Union[str, None] = '5f3e8a9d2c1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Create two_factor_config table
    op.create_table('two_factor_config',
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('is_enabled', sa.Boolean(), nullable=False, server_default='false'),
        sa.Column('primary_method', sa.String(length=20), nullable=False, server_default='totp'),
        sa.Column('totp_secret', sa.String(length=255), nullable=True),
        sa.Column('totp_verified_at', sa.DateTime(), nullable=True),
        sa.Column('backup_codes', sa.JSON(), nullable=True),
        sa.Column('backup_codes_generated_at', sa.DateTime(), nullable=True),
        sa.Column('phone_number', sa.String(length=50), nullable=True),
        sa.Column('phone_verified_at', sa.DateTime(), nullable=True),
        sa.Column('last_used_at', sa.DateTime(), nullable=True),
        sa.Column('failed_attempts', sa.Integer(), nullable=False, server_default='0'),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('external_id', sa.String(length=255), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('CURRENT_TIMESTAMP')),
        sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.text('CURRENT_TIMESTAMP')),
        sa.Column('created_by_id', sa.UUID(), nullable=True),
        sa.Column('updated_by_id', sa.UUID(), nullable=True),
        sa.Column('deleted_at', sa.DateTime(), nullable=True),
        sa.Column('deleted_by_id', sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_id')
    )
    op.create_index('ix_two_factor_config_external_id', 'two_factor_config', ['external_id'], unique=True)

    # Create sms_verification table
    op.create_table('sms_verification',
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('phone_number', sa.String(length=50), nullable=False),
        sa.Column('code', sa.String(length=10), nullable=False),
        sa.Column('purpose', sa.String(length=50), nullable=False),
        sa.Column('is_used', sa.Boolean(), nullable=False, server_default='false'),
        sa.Column('used_at', sa.DateTime(), nullable=True),
        sa.Column('expires_at', sa.DateTime(), nullable=False),
        sa.Column('ip_address', sa.String(length=50), nullable=True),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('external_id', sa.String(length=255), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('CURRENT_TIMESTAMP')),
        sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.text('CURRENT_TIMESTAMP')),
        sa.Column('created_by_id', sa.UUID(), nullable=True),
        sa.Column('updated_by_id', sa.UUID(), nullable=True),
        sa.Column('deleted_at', sa.DateTime(), nullable=True),
        sa.Column('deleted_by_id', sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )

    # Create index on external_id and phone_number for faster lookups
    op.create_index('ix_sms_verification_external_id', 'sms_verification', ['external_id'], unique=True)
    op.create_index('ix_sms_verification_phone_number', 'sms_verification', ['phone_number'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sms_verification_phone_number', table_name='sms_verification')
    op.drop_index('ix_sms_verification_external_id', table_name='sms_verification')
    op.drop_table('sms_verification')
    op.drop_index('ix_two_factor_config_external_id', table_name='two_factor_config')
    op.drop_table('two_factor_config')
    # ### end Alembic commands ###
