# Generated by Django 5.0.7 on 2025-10-04 15:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Identifiant unique pour les intégrations externes', unique=True, verbose_name='External ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Modifié le')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Marqué comme supprimé (soft delete)', verbose_name='Supprimé')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Supprimé le')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Données additionnelles au format JSON', verbose_name='Métadonnées')),
                ('name', models.CharField(help_text='Nom technique du module (ex: crm, inventory, accounting)', max_length=100, unique=True, verbose_name='Nom du module')),
                ('display_name', models.CharField(help_text='Nom convivial du module', max_length=200, verbose_name="Nom d'affichage")),
                ('description', models.TextField(blank=True, help_text='Description détaillée du module', verbose_name='Description')),
                ('version', models.CharField(help_text='Version du module (ex: 1.0.0)', max_length=20, verbose_name='Version')),
                ('is_installed', models.BooleanField(default=False, help_text='Le module est installé', verbose_name='Installé')),
                ('is_active', models.BooleanField(default=False, help_text='Le module est activé', verbose_name='Actif')),
                ('is_core', models.BooleanField(default=False, help_text='Module du système (non désinstallable)', verbose_name='Module core')),
                ('author', models.CharField(blank=True, help_text='Auteur du module', max_length=200, verbose_name='Auteur')),
                ('icon', models.CharField(blank=True, help_text='Icône UI5 du module', max_length=50, verbose_name='Icône')),
                ('category', models.CharField(blank=True, help_text='Catégorie du module (CRM, Finance, RH, etc.)', max_length=100, verbose_name='Catégorie')),
                ('dependencies', models.JSONField(blank=True, default=list, help_text='Liste des modules requis (JSON array)', verbose_name='Dépendances')),
                ('license_key', models.CharField(blank=True, help_text='Clé de licence du module', max_length=500, verbose_name='Clé de licence')),
                ('license_type', models.CharField(blank=True, help_text='Type de licence (free, commercial, trial)', max_length=50, verbose_name='Type de licence')),
                ('install_date', models.DateTimeField(blank=True, null=True, verbose_name="Date d'installation")),
                ('config', models.JSONField(blank=True, default=dict, help_text='Configuration spécifique du module (JSON)', verbose_name='Configuration')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Supprimé par')),
                ('installed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installed_modules', to=settings.AUTH_USER_MODEL, verbose_name='Installé par')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
            ],
            options={
                'verbose_name': 'Module',
                'verbose_name_plural': 'Modules',
                'ordering': ['display_name'],
            },
        ),
        migrations.CreateModel(
            name='ModuleInstallation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Identifiant unique pour les intégrations externes', unique=True, verbose_name='External ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Modifié le')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Marqué comme supprimé (soft delete)', verbose_name='Supprimé')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Supprimé le')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Données additionnelles au format JSON', verbose_name='Métadonnées')),
                ('action', models.CharField(choices=[('install', 'Installation'), ('uninstall', 'Désinstallation'), ('activate', 'Activation'), ('deactivate', 'Désactivation'), ('update', 'Mise à jour')], max_length=20, verbose_name='Action')),
                ('version', models.CharField(max_length=20, verbose_name='Version')),
                ('status', models.CharField(choices=[('success', 'Succès'), ('failed', 'Échec'), ('pending', 'En cours')], default='pending', max_length=20, verbose_name='Statut')),
                ('error_message', models.TextField(blank=True, verbose_name="Message d'erreur")),
                ('execution_time', models.FloatField(blank=True, null=True, verbose_name="Temps d'exécution (secondes)")),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Supprimé par')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installation_history', to='modules.module', verbose_name='Module')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='module_actions', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Installation Module',
                'verbose_name_plural': 'Installations Module',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ModulePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Identifiant unique pour les intégrations externes', unique=True, verbose_name='External ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Modifié le')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Marqué comme supprimé (soft delete)', verbose_name='Supprimé')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Supprimé le')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Données additionnelles au format JSON', verbose_name='Métadonnées')),
                ('codename', models.CharField(help_text='Code de la permission (ex: can_export_data)', max_length=100, verbose_name='Code')),
                ('name', models.CharField(help_text='Nom descriptif de la permission', max_length=255, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Supprimé par')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_permissions', to='modules.module', verbose_name='Module')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
            ],
            options={
                'verbose_name': 'Permission Module',
                'verbose_name_plural': 'Permissions Module',
            },
        ),
        migrations.AddIndex(
            model_name='module',
            index=models.Index(fields=['name'], name='modules_mod_name_07111e_idx'),
        ),
        migrations.AddIndex(
            model_name='module',
            index=models.Index(fields=['is_active', 'is_installed'], name='modules_mod_is_acti_397777_idx'),
        ),
        migrations.AddIndex(
            model_name='moduleinstallation',
            index=models.Index(fields=['module', '-created_at'], name='modules_mod_module__4850c4_idx'),
        ),
        migrations.AddIndex(
            model_name='moduleinstallation',
            index=models.Index(fields=['action', 'status'], name='modules_mod_action_061f4d_idx'),
        ),
        migrations.AddIndex(
            model_name='modulepermission',
            index=models.Index(fields=['module', 'codename'], name='modules_mod_module__ece528_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='modulepermission',
            unique_together={('module', 'codename')},
        ),
    ]
