/**
 * Expo config plugin — Network Security Config + Certificate Pinning.
 *
 * Because we ship via the Expo managed workflow there's no
 * `android/app/src/main` directory we can edit by hand. This plugin
 * runs during `expo prebuild` and:
 *   1. Writes `res/xml/network_security_config.xml` with per-domain
 *      pinning + cleartext-deny, using `withDangerousMod`.
 *   2. Adds `android:networkSecurityConfig="@xml/network_security_config"`
 *      to the `<application>` tag via `withAndroidManifest`.
 *
 * Pin rotation: Android Pinning refuses ALL connections if no pinned
 * SPKI hash matches the server chain. Renewing the TLS cert without
 * updating this file = app stops talking to the backend. Add a
 * backup pin BEFORE deploying the next cert, or pin the intermediate
 * CA instead of the leaf for a longer grace window.
 *
 * Docs: https://developer.android.com/training/articles/security-config
 */

const { withAndroidManifest, withDangerousMod } = require("@expo/config-plugins");
const fs = require("fs");
const path = require("path");

/**
 * Pin set — SHA-256 of the SubjectPublicKeyInfo of each host's leaf
 * cert. Obtained with:
 *   openssl s_client -servername HOST -connect HOST:443 </dev/null \
 *     | openssl x509 -pubkey -noout \
 *     | openssl pkey -pubin -outform der \
 *     | openssl dgst -sha256 -binary \
 *     | openssl base64
 */
const PINS = {
  "api.opsflux.io": ["11+zVyEezUGnSGyOlK5jmEwokDCCwWApznEmkipK5TE="],
  "app.opsflux.io": ["8Gqx6/aQmgsQv5DFY8Ha+eyHnzuEepy3HYJe8xdIL94="],
};

function buildNetworkSecurityXml() {
  const domains = Object.entries(PINS)
    .map(([host, pins]) => {
      const pinEntries = pins
        .map((h) => `      <pin digest="SHA-256">${h}</pin>`)
        .join("\n");
      return [
        `  <domain-config cleartextTrafficPermitted="false">`,
        `    <domain includeSubdomains="false">${host}</domain>`,
        `    <pin-set>`,
        pinEntries,
        `    </pin-set>`,
        `  </domain-config>`,
      ].join("\n");
    })
    .join("\n");

  return `<?xml version="1.0" encoding="utf-8"?>
<!--
  Auto-generated by withNetworkSecurityConfig.js — do not edit by hand.
  Source of truth: apps/mobile/plugins/withNetworkSecurityConfig.js
-->
<network-security-config>
${domains}
  <base-config cleartextTrafficPermitted="false">
    <trust-anchors>
      <certificates src="system" />
    </trust-anchors>
  </base-config>
</network-security-config>
`;
}

const withNetworkSecurityConfigFile = (config) => {
  return withDangerousMod(config, [
    "android",
    async (cfg) => {
      const xmlDir = path.join(
        cfg.modRequest.platformProjectRoot,
        "app/src/main/res/xml"
      );
      fs.mkdirSync(xmlDir, { recursive: true });
      fs.writeFileSync(
        path.join(xmlDir, "network_security_config.xml"),
        buildNetworkSecurityXml(),
        "utf8"
      );
      return cfg;
    },
  ]);
};

const withNetworkSecurityConfigManifest = (config) => {
  return withAndroidManifest(config, (cfg) => {
    const application = cfg.modResults.manifest.application?.[0];
    if (!application) {
      throw new Error(
        "[withNetworkSecurityConfig] <application> tag not found in AndroidManifest"
      );
    }
    application.$ = application.$ ?? {};
    application.$["android:networkSecurityConfig"] =
      "@xml/network_security_config";
    return cfg;
  });
};

module.exports = function withNetworkSecurityConfig(config) {
  config = withNetworkSecurityConfigFile(config);
  config = withNetworkSecurityConfigManifest(config);
  return config;
};
