"""Atomic reference number generation with PostgreSQL advisory lock.

Every business object (asset, tier, project, etc.) gets a unique code
generated by ``generate_reference(prefix, db)``.

The format is configurable via a template stored in the Settings DB or
passed explicitly:
  - ``AST-{YYYY}-{####}``   -> AST-2026-0001
  - ``TRS-{####}``          -> TRS-0001
  - ``PRJ-{YY}-{######}``   -> PRJ-26-000001

Default template: ``{prefix}-{YYYY}-{####}``

Atomicity is guaranteed by ``pg_advisory_xact_lock(hashtext(prefix||year))``.
"""

from __future__ import annotations

import logging
import re
from datetime import UTC, datetime
from uuid import UUID

from sqlalchemy import select, text
from sqlalchemy.ext.asyncio import AsyncSession

from app.models.common import ReferenceSequence, Setting

logger = logging.getLogger(__name__)

# Matches template placeholders: {YYYY}, {YY}, {####}, {prefix}
_PLACEHOLDER_RE = re.compile(r"\{([^}]+)\}")

# Default template when nothing is configured
DEFAULT_TEMPLATE = "{prefix}-{YYYY}-{####}"


def _resolve_template(
    template: str,
    prefix: str,
    year: int,
    seq_value: int,
    *,
    context: dict[str, str] | None = None,
) -> str:
    """Replace template placeholders with actual values.

    Supported placeholders (like Dolibarr numbering modules):
      {prefix}        — the prefix string (e.g. "ADS")
      {YYYY}          — four-digit year (2026)
      {YY}            — two-digit year (26)
      {MM}            — two-digit month (03)
      {DD}            — two-digit day (19)
      {####}          — zero-padded sequence (width = number of # chars, min 4)
      {######}        — six-digit zero-padded sequence
      {entity_code}   — entity code (e.g. "PCR", "PCC")
      {entity_name}   — entity full name
      {asset_code}    — asset code (if applicable)
      {project_code}  — project code (if applicable)
      {type}          — object type/subtype (e.g. "pid", "maintenance")
      {user_initials} — creator initials (e.g. "HB")

    Examples:
      "ADS-{entity_code}-{YYYY}-{#####}"  -> "ADS-PCR-2026-00042"
      "{entity_code}/{type}/{YYYY}{MM}-{####}" -> "PCR/PID/202603-0001"
      "{prefix}-{YYYY}-{######}"  -> "VYG-2026-000123"
    """
    now = datetime.now(UTC)
    ctx = context or {}

    def _replace(match: re.Match) -> str:
        token = match.group(1)

        if token == "prefix":
            return prefix
        if token == "YYYY":
            return str(year)
        if token == "YY":
            return str(year)[-2:]
        if token == "MM":
            return str(now.month).zfill(2)
        if token == "DD":
            return str(now.day).zfill(2)

        # Context-based variables (entity, project, asset, type, user)
        if token in ("entity_code", "entity_name", "asset_code", "project_code", "type", "user_initials"):
            return ctx.get(token, "")

        # Sequence padding — any run of # characters
        if set(token) == {"#"}:
            width = max(len(token), 4)
            return str(seq_value).zfill(width)

        # Unknown placeholder — leave as-is
        return match.group(0)

    return _PLACEHOLDER_RE.sub(_replace, template)


async def _get_template_from_settings(
    prefix: str,
    entity_id: UUID | None,
    db: AsyncSession,
) -> str | None:
    """Look up a custom reference template from the Settings table.

    Key convention: ``reference_template:{PREFIX}`` (e.g. ``reference_template:AST``).
    The value JSON is expected to be ``{"template": "AST-{YYYY}-{####}"}``.
    """
    key = f"reference_template:{prefix}"

    query = select(Setting).where(Setting.key == key)
    if entity_id is not None:
        # Prefer entity-scoped setting, fall back to tenant-scoped
        query = query.where((Setting.scope_id == str(entity_id)) | (Setting.scope == "tenant")).order_by(
            # Entity-specific first
            Setting.scope.desc()
        )
    result = await db.execute(query.limit(1))
    setting = result.scalar_one_or_none()

    if setting and isinstance(setting.value, dict):
        return setting.value.get("template")
    return None


async def generate_reference(
    prefix: str,
    db: AsyncSession,
    *,
    entity_id: UUID | None = None,
    template: str | None = None,
    context: dict[str, str] | None = None,
) -> str:
    """Generate the next reference number for a given prefix.

    Uses PostgreSQL advisory lock for atomicity (no race conditions).
    The ``ReferenceSequence`` table tracks ``(prefix, year, last_value)``.

    Default template: ``{prefix}-{YYYY}-{####}`` where ``####`` = zero-padded
    sequence number.

    Parameters
    ----------
    prefix : str
        Business object prefix, e.g. ``"ADS"``, ``"VYG"``, ``"ACT"``.
    db : AsyncSession
        Active database session (must be inside a transaction).
    entity_id : UUID | None
        Optional entity scope — used for looking up per-entity template
        settings and auto-populating {entity_code}/{entity_name}.
    template : str | None
        Explicit template override. If not provided, the function checks the
        Settings DB, then falls back to ``DEFAULT_TEMPLATE``.
    context : dict[str, str] | None
        Additional substitution variables:
        - entity_code, entity_name (auto-populated if entity_id given)
        - asset_code, project_code, type, user_initials

    Returns
    -------
    str
        The generated reference string, e.g. ``"ADS-PCR-2026-00042"``.

    Examples
    --------
    >>> ref = await generate_reference("ADS", db, entity_id=eid)
    "ADS-2026-0001"
    >>> ref = await generate_reference("ADS", db, entity_id=eid,
    ...     context={"entity_code": "PCR"})
    "ADS-PCR-2026-0001"  # if template is "{prefix}-{entity_code}-{YYYY}-{####}"
    """
    year = datetime.now(UTC).year

    # Derive a stable positive int32 lock key from prefix + year
    lock_key = hash(f"{prefix}:{year}") & 0x7FFFFFFF

    # Acquire advisory lock (released automatically at transaction end)
    await db.execute(text(f"SELECT pg_advisory_xact_lock({lock_key})"))

    # Upsert: insert or increment last_value atomically
    result = await db.execute(
        text(
            "INSERT INTO reference_sequences (prefix, year, last_value) "
            "VALUES (:prefix, :year, 1) "
            "ON CONFLICT (prefix, year) "
            "DO UPDATE SET last_value = reference_sequences.last_value + 1 "
            "RETURNING last_value"
        ),
        {"prefix": prefix, "year": year},
    )
    seq_value = result.scalar_one()

    # Auto-populate entity_code/entity_name from DB if entity_id given
    ctx = dict(context or {})
    if entity_id and "entity_code" not in ctx:
        ent_result = await db.execute(
            text("SELECT code, name FROM entities WHERE id = :eid"),
            {"eid": str(entity_id)},
        )
        ent_row = ent_result.first()
        if ent_row:
            ctx.setdefault("entity_code", ent_row[0] or "")
            ctx.setdefault("entity_name", ent_row[1] or "")

    # Resolve template (explicit > Settings DB > default)
    if template is None:
        template = await _get_template_from_settings(prefix, entity_id, db)
    if template is None:
        template = DEFAULT_TEMPLATE

    reference = _resolve_template(template, prefix, year, seq_value, context=ctx)
    logger.debug("Generated reference: %s (prefix=%s, seq=%d)", reference, prefix, seq_value)
    return reference


async def preview_reference(
    prefix: str,
    db: AsyncSession,
    *,
    entity_id: UUID | None = None,
    template: str | None = None,
    context: dict[str, str] | None = None,
) -> str:
    """Preview what the next reference will look like *without consuming it*.

    This reads the current ``last_value`` and computes ``last_value + 1``
    without actually incrementing.

    Parameters
    ----------
    prefix : str
        Business object prefix.
    db : AsyncSession
        Active database session.
    entity_id : UUID | None
        Optional entity scope for template lookup.
    template : str | None
        Explicit template override.
    context : dict[str, str] | None
        Additional substitution variables (same as ``generate_reference``):
        entity_code, entity_name, asset_code, project_code, type, user_initials.

    Returns
    -------
    str
        The *next* reference string that ``generate_reference`` would return.
    """
    year = datetime.now(UTC).year

    # Read current value (no lock needed — this is a preview)
    result = await db.execute(
        select(ReferenceSequence.last_value).where(
            ReferenceSequence.prefix == prefix,
            ReferenceSequence.year == year,
        )
    )
    current_value = result.scalar_one_or_none()
    next_value = (current_value or 0) + 1

    # Auto-populate entity_code/entity_name from DB if entity_id given
    ctx = dict(context or {})
    if entity_id and "entity_code" not in ctx:
        ent_result = await db.execute(
            text("SELECT code, name FROM entities WHERE id = :eid"),
            {"eid": str(entity_id)},
        )
        ent_row = ent_result.first()
        if ent_row:
            ctx.setdefault("entity_code", ent_row[0] or "")
            ctx.setdefault("entity_name", ent_row[1] or "")

    # Resolve template
    if template is None:
        template = await _get_template_from_settings(prefix, entity_id, db)
    if template is None:
        template = DEFAULT_TEMPLATE

    return _resolve_template(template, prefix, year, next_value, context=ctx)
